rm(list = ls())
library(forecast)
#data = arima.sim(list(order=c(3,0,2), ma=c(0.5,-0.3), ar=c(0.4, -0.2, 0.15)), n = 5000)
data = arima.sim(list(order=c(1,2,1),ma=c(5), ar=c(0, 3, -2)), n = 10)
par(mfcol = c(3,1))
plot(data, main='ARMA Simulation Original Signal')
acf(data, type='correlation', main='ACF')
acf(data, type='partial', main='PACF')
#print(auto.arima(data))